 $episodes = {
    "rose": 1,
    "the end of the world": 2,
    "the unquiet dead": 3,
    "aliens of london": 4,
    "world war three": 5,
    "dalek": 6,
    "the long game": 7,
    "father's day": 8,
    "the empty child": 9,
    "the doctor dances": 10,
    "boom town": 11,
    "bad wolf": 12,
    "the parting of the ways": 13,
    "the christmas invasion": 14,
    "new earth": 15,
    "tooth and claw": 16,
    "school reunion": 17,
    "girl in the fireplace": 18,
    "rise of the cybermen": 19,
    "age of steel": 20,
    "the idiot's lantern": 21,
    "the impossible planet": 22,
    "the satan pit": 23,
    "love & monsters": 24,
    "fear her": 25,
    "army of ghosts": 26,
    "doomsday": 27,
    "the runaway bride": 28,
    "smith and jones": 29,
    "the shakespear code": 30,
    "gridlock": 31,
    "daleks in manhattan": 32,
    "evolution of the daleks": 33,
    "the lazarus experiment": 34,
    "42": 35,
    "human nature": 36,
    "the family of blood": 37,
    "blink": 38,
    "utopia": 39,
    "the sound of drums": 40,
    "last of the time lords": 41,
    "voyage of the damned": 42,
    "partners in crime": 43,
    "the fires of pompeii": 44,
    "the poisoned sky": 45,
    "the doctor's daughter": 46,
    "the unicorn and the wasp": 47,
    "silence in the library": 48,
    "forest of the dead": 49,
    "midnight": 50,
    "turn left": 51,
    "the stolen earth": 52,
    "journey's end": 53,
    "the next doctor": 54,
    "planet of the dead": 55,
    "the waters of mars": 56,
    "the end of time": 57,
    "the eleventh hour": 58,
    "the beast below": 59,
    "victory of the daleks": 60,
    "the time of angels": 61,
    "flesh and stone": 62,
    "vincent and the doctor": 63,
    "amy's choice": 64,
    "the hungry earth": 65,
    "cold blood": 66,
    "vince and the doctor": 67,
    "the lodger": 68,
    "the pandorica opens": 69,
    "the big bang": 70,
    "a christmas carol": 71
}

def getRandom() 
    puts $episodes.keys.sample
end